services:
  - type: web
    name: signaling-server
    env: bun
    region: oregon
    plan: free
    buildCommand: bun install
    startCommand: bun run server.js
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health